export const carouselItems = [
  {
    id: 1,
    imageUrl: "/assets/outhers/CarouselBanner.png",
    title: "Tecnologia da Informação 1",
    technology: "Programação",
    isEad: true,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mattis sagittis sem sit amet vehicula. Aenean viverra ligula nec imperdiet tristique. Nulla eleifend ipsum eu aliquam pharetra. Vivamus vitae lorem finibus, convallis odio sed, sagittis est. Vestibulum tempus vel libero non vestibulum.",
    cashValue: 120.5,
    installmentValue: 12.5,
    numberOfInstallments: 10,
    workload: "240h",
    offeredBy: "SENAI SQ",
  },
  {
    id: 2,
    imageUrl: "/assets/outhers/CarouselBanner.png",
    title: "Tecnologia da Informação 2",
    technology: "Redes de Computadores",
    isEad: true,
    description:
      "Este curso aborda configuração e manutenção de redes de computadores. Aprenda desde os fundamentos até soluções avançadas, com foco na prática. Ideal para quem deseja se especializar em redes corporativas e infraestrutura de TI.",
    cashValue: 200.0,
    installmentValue: 20.0,
    numberOfInstallments: 10,
    workload: "300h",
    offeredBy: "SENAI SC",
  },
  {
    id: 3,
    imageUrl: "/assets/outhers/CarouselBanner.png",
    title: "Tecnologia da Informação 3",
    technology: "Segurança da Informação",
    isEad: false,
    description:
      "Aprenda a proteger sistemas e dados contra ameaças cibernéticas. Desenvolva habilidades para implementar políticas de segurança, realizar auditorias e prevenir ataques cibernéticos em ambientes corporativos.",
    cashValue: 150.0,
    installmentValue: 15.0,
    numberOfInstallments: 10,
    workload: "180h",
    offeredBy: "SENAI RJ",
  },
  {
    id: 4,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 4",
    technology: "Inteligência Artificial",
    isEad: true,
    description:
      "Curso introdutório sobre inteligência artificial e aprendizado de máquina. Explore algoritmos modernos, redes neurais e aplicações práticas em diferentes setores. Perfeito para iniciantes interessados em IA.",
    cashValue: 300.0,
    installmentValue: 30.0,
    numberOfInstallments: 10,
    workload: "360h",
    offeredBy: "SENAI SP",
  },
  {
    id: 5,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 5",
    technology: "Desenvolvimento Web",
    isEad: false,
    description:
      "Domine tecnologias como HTML, CSS, JavaScript e frameworks modernos para criar aplicações web responsivas e dinâmicas. Este curso é ideal para quem deseja ingressar na carreira de desenvolvimento web.",
    cashValue: 180.0,
    installmentValue: 18.0,
    numberOfInstallments: 10,
    workload: "200h",
    offeredBy: "SENAI MG",
  },
  {
    id: 6,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 6",
    technology: "Desenvolvimento Mobile",
    isEad: true,
    description:
      "Aprenda a desenvolver aplicativos para Android e iOS com tecnologias modernas. Este curso abrange desde o design de interfaces até a integração de APIs, oferecendo uma experiência completa em desenvolvimento mobile.",
    cashValue: 250.0,
    installmentValue: 25.0,
    numberOfInstallments: 10,
    workload: "280h",
    offeredBy: "SENAI BA",
  },
  {
    id: 7,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 7",
    technology: "Banco de Dados",
    isEad: false,
    description:
      "Aprenda a projetar, administrar e otimizar bancos de dados relacionais e não relacionais. Desenvolva habilidades práticas em SQL e gerenciamento de grandes volumes de dados.",
    cashValue: 220.0,
    installmentValue: 22.0,
    numberOfInstallments: 10,
    workload: "250h",
    offeredBy: "SENAI PE",
  },
  {
    id: 8,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 8",
    technology: "Big Data",
    isEad: true,
    description:
      "Entenda os conceitos de Big Data e como trabalhar com análise de dados em larga escala. Explore ferramentas como Hadoop e Spark para lidar com grandes volumes de informações.",
    cashValue: 350.0,
    installmentValue: 35.0,
    numberOfInstallments: 10,
    workload: "400h",
    offeredBy: "SENAI DF",
  },
  {
    id: 9,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 9",
    technology: "Machine Learning",
    isEad: true,
    description:
      "Introdução prática aos conceitos de aprendizado de máquina. Aplique técnicas para modelar dados de maneira eficiente. Explore bibliotecas populares como TensorFlow e PyTorch.",
    cashValue: 400.0,
    installmentValue: 40.0,
    numberOfInstallments: 10,
    workload: "320h",
    offeredBy: "SENAI GO",
  },
  {
    id: 10,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 10",
    technology: "Engenharia de Software",
    isEad: false,
    description:
      "Aprenda sobre práticas modernas de desenvolvimento de software, como design patterns, arquitetura de sistemas e metodologias ágeis. Ideal para quem deseja criar soluções robustas e escaláveis.",
    cashValue: 500.0,
    installmentValue: 50.0,
    numberOfInstallments: 10,
    workload: "400h",
    offeredBy: "SENAI RS",
  },
  {
    id: 11,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 11",
    technology: "Cloud Computing",
    isEad: true,
    description:
      "Descubra os fundamentos de computação em nuvem. Gerencie infraestrutura com AWS, Azure e Google Cloud. Desenvolva aplicações escaláveis e seguras.",
    cashValue: 600.0,
    installmentValue: 60.0,
    numberOfInstallments: 10,
    workload: "420h",
    offeredBy: "SENAI AM",
  },
  {
    id: 12,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 12",
    technology: "IoT (Internet das Coisas)",
    isEad: true,
    description:
      "Entenda os fundamentos de IoT e suas aplicações. Desenvolva soluções conectadas para dispositivos inteligentes. Explore arquiteturas e protocolos de comunicação.",
    cashValue: 700.0,
    installmentValue: 70.0,
    numberOfInstallments: 10,
    workload: "480h",
    offeredBy: "SENAI PR",
  },
  {
    id: 13,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 13",
    technology: "Cybersecurity",
    isEad: true,
    description:
      "Aprenda como proteger sistemas e redes contra ataques cibernéticos. Desenvolva habilidades práticas em criptografia, firewalls e monitoramento de ameaças.",
    cashValue: 750.0,
    installmentValue: 75.0,
    numberOfInstallments: 10,
    workload: "500h",
    offeredBy: "SENAI SC",
  },
  {
    id: 14,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 14",
    technology: "Análise de Dados",
    isEad: true,
    description:
      "Descubra como coletar, organizar e interpretar dados para tomar decisões informadas. Aprenda ferramentas como Excel, Power BI e Python para análise de dados.",
    cashValue: 650.0,
    installmentValue: 65.0,
    numberOfInstallments: 10,
    workload: "360h",
    offeredBy: "SENAI SP",
  },
  {
    id: 15,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 15",
    technology: "DevOps",
    isEad: false,
    description:
      "Explore a integração entre desenvolvimento e operações de TI. Aprenda a criar pipelines automatizados e a trabalhar com ferramentas como Docker e Kubernetes.",
    cashValue: 850.0,
    installmentValue: 85.0,
    numberOfInstallments: 10,
    workload: "400h",
    offeredBy: "SENAI RS",
  },
  {
    id: 16,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 16",
    technology: "Automação de Processos",
    isEad: true,
    description:
      "Entenda como automatizar processos empresariais com o uso de tecnologias avançadas. Desenvolva habilidades em RPA e integração de sistemas.",
    cashValue: 780.0,
    installmentValue: 78.0,
    numberOfInstallments: 10,
    workload: "320h",
    offeredBy: "SENAI MG",
  },
  {
    id: 17,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 17",
    technology: "Design UX/UI",
    isEad: true,
    description:
      "Aprenda a projetar experiências de usuário eficazes e interfaces visuais atraentes. Desenvolva habilidades práticas em ferramentas como Figma e Adobe XD.",
    cashValue: 500.0,
    installmentValue: 50.0,
    numberOfInstallments: 10,
    workload: "300h",
    offeredBy: "SENAI RJ",
  },
  {
    id: 18,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 18",
    technology: "Blockchain",
    isEad: false,
    description:
      "Compreenda os fundamentos do blockchain e suas aplicações em negócios e tecnologia. Explore como implementar soluções descentralizadas seguras.",
    cashValue: 900.0,
    installmentValue: 90.0,
    numberOfInstallments: 10,
    workload: "480h",
    offeredBy: "SENAI DF",
  },
  {
    id: 19,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 19",
    technology: "Realidade Aumentada e Virtual",
    isEad: true,
    description:
      "Descubra como criar experiências imersivas usando tecnologias de realidade aumentada e virtual. Ideal para profissionais de desenvolvimento e design.",
    cashValue: 950.0,
    installmentValue: 95.0,
    numberOfInstallments: 10,
    workload: "420h",
    offeredBy: "SENAI AM",
  },
  {
    id: 20,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 20",
    technology: "Redes Neurais",
    isEad: true,
    description:
      "Explore os conceitos de redes neurais e como utilizá-las para resolver problemas complexos. Aprenda frameworks populares como TensorFlow e Keras.",
    cashValue: 800.0,
    installmentValue: 80.0,
    numberOfInstallments: 10,
    workload: "360h",
    offeredBy: "SENAI BA",
  },
  {
    id: 21,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 21",
    technology: "Engenharia de Dados",
    isEad: false,
    description:
      "Aprenda a criar e gerenciar pipelines de dados para grandes volumes de informações. Ideal para quem deseja trabalhar com Big Data e Analytics.",
    cashValue: 1000.0,
    installmentValue: 100.0,
    numberOfInstallments: 10,
    workload: "500h",
    offeredBy: "SENAI GO",
  },
  {
    id: 22,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 22",
    technology: "Robótica",
    isEad: false,
    description:
      "Introdução ao desenvolvimento de robôs para automação e soluções industriais. Aprenda desde a mecânica até a programação de robôs.",
    cashValue: 1100.0,
    installmentValue: 110.0,
    numberOfInstallments: 10,
    workload: "600h",
    offeredBy: "SENAI SP",
  },
  {
    id: 23,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 23",
    technology: "Virtualização de Sistemas",
    isEad: true,
    description:
      "Domine conceitos de virtualização para otimizar o uso de recursos de TI. Trabalhe com ferramentas como VMware e Hyper-V para criar ambientes escaláveis.",
    cashValue: 880.0,
    installmentValue: 88.0,
    numberOfInstallments: 10,
    workload: "360h",
    offeredBy: "SENAI PE",
  },
  {
    id: 24,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 24",
    technology: "Game Development",
    isEad: true,
    description:
      "Aprenda a criar jogos desde o conceito inicial até a implementação final. Explore engines como Unity e Unreal para criar experiências interativas.",
    cashValue: 950.0,
    installmentValue: 95.0,
    numberOfInstallments: 10,
    workload: "480h",
    offeredBy: "SENAI MG",
  },
  {
    id: 25,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 25",
    technology: "Automação Industrial",
    isEad: false,
    description:
      "Entenda como implementar e gerenciar sistemas automatizados em processos industriais. Desenvolva habilidades em controladores lógicos programáveis (CLP) e sensores.",
    cashValue: 1150.0,
    installmentValue: 115.0,
    numberOfInstallments: 10,
    workload: "600h",
    offeredBy: "SENAI SC",
  },
];
