export const carouselItems: ICourseCard[] = [
  {
    id: 1,
    imageUrl: "/assets/outhers/CarouselBanner.png",
    title: "Tecnologia da Informação 1",
    technology: "Programação",
    isEad: true,
    description:
      "Aprenda os fundamentos de programação e lógica computacional. aldjlka  jldjasl jdlksa jlkdjsalkdlksaj dlksajldkjsal jsalk dlksa",
    cashValue: 120.5,
    installmentValue: 12.5,
    numberOfInstallments: 10,
  },
  {
    id: 2,
    imageUrl: "/assets/outhers/CarouselBanner.png",
    title: "Tecnologia da Informação 2",
    technology: "Redes de Computadores",
    isEad: true,
    description: "Curso avançado sobre configuração e manutenção de redes.",
    cashValue: 200.0,
    installmentValue: 20.0,
    numberOfInstallments: 10,
  },
  {
    id: 3,
    imageUrl: "/assets/outhers/CarouselBanner.png",
    title: "Tecnologia da Informação 3",
    technology: "Segurança da Informação",
    isEad: false,
    description:
      "Aprenda a proteger sistemas e dados contra ameaças cibernéticas.",
    cashValue: 150.0,
    installmentValue: 15.0,
    numberOfInstallments: 10,
  },
  {
    id: 4,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 4",
    technology: "Inteligência Artificial",
    isEad: true,
    description:
      "Curso introdutório sobre algoritmos de IA e aprendizado de máquina.",
    cashValue: 300.0,
    installmentValue: 30.0,
    numberOfInstallments: 10,
  },
  {
    id: 5,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 5",
    technology: "Desenvolvimento Web",
    isEad: false,
    description:
      "Domine as principais tecnologias para criar aplicações web modernas.",
    cashValue: 180.0,
    installmentValue: 18.0,
    numberOfInstallments: 10,
  },
  {
    id: 6,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 6",
    technology: "Desenvolvimento Mobile",
    isEad: true,
    description:
      "Curso completo sobre criação de aplicativos para Android e iOS.",
    cashValue: 250.0,
    installmentValue: 25.0,
    numberOfInstallments: 10,
  },
  {
    id: 7,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 7",
    technology: "Banco de Dados",
    isEad: false,
    description: "Aprenda a projetar, administrar e otimizar bancos de dados.",
    cashValue: 220.0,
    installmentValue: 22.0,
    numberOfInstallments: 10,
  },
  {
    id: 8,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 8",
    technology: "Big Data",
    isEad: true,
    description:
      "Entenda os conceitos de Big Data e análise de dados em larga escala.",
    cashValue: 350.0,
    installmentValue: 35.0,
    numberOfInstallments: 10,
  },
  {
    id: 9,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 9",
    technology: "Computação em Nuvem",
    isEad: true,
    description: "Curso completo sobre AWS, Azure e Google Cloud.",
    cashValue: 400.0,
    installmentValue: 40.0,
    numberOfInstallments: 10,
  },
  {
    id: 10,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 10",
    technology: "DevOps",
    isEad: false,
    description: "Automatize processos e melhore fluxos de trabalho.",
    cashValue: 280.0,
    installmentValue: 28.0,
    numberOfInstallments: 10,
  },
  {
    id: 11,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 11",
    technology: "Ciência de Dados",
    isEad: true,
    description: "Transforme dados em insights valiosos para empresas.",
    cashValue: 320.0,
    installmentValue: 32.0,
    numberOfInstallments: 10,
  },
  {
    id: 12,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 12",
    technology: "Robótica",
    isEad: false,
    description: "Crie e programe robôs para diversas aplicações na indústria.",
    cashValue: 500.0,
    installmentValue: 50.0,
    numberOfInstallments: 10,
  },
  {
    id: 13,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 13",
    technology: "Engenharia de Software",
    isEad: true,
    description: "Domine práticas modernas de desenvolvimento de software.",
    cashValue: 420.0,
    installmentValue: 42.0,
    numberOfInstallments: 10,
  },
  {
    id: 14,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 14",
    technology: "Realidade Virtual",
    isEad: false,
    description: "Crie experiências imersivas com tecnologias de VR.",
    cashValue: 450.0,
    installmentValue: 45.0,
    numberOfInstallments: 10,
  },
  {
    id: 15,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 15",
    technology: "Realidade Aumentada",
    isEad: true,
    description: "Desenvolva aplicativos com AR para diferentes plataformas.",
    cashValue: 300.0,
    installmentValue: 30.0,
    numberOfInstallments: 10,
  },
  {
    id: 16,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 16",
    technology: "Blockchain",
    isEad: false,
    description: "Aprenda os fundamentos de Blockchain e criptomoedas.",
    cashValue: 550.0,
    installmentValue: 55.0,
    numberOfInstallments: 10,
  },
  {
    id: 17,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 17",
    technology: "Design UX/UI",
    isEad: true,
    description: "Crie interfaces e experiências incríveis para usuários.",
    cashValue: 320.0,
    installmentValue: 32.0,
    numberOfInstallments: 10,
  },
  {
    id: 18,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 18",
    technology: "Análise de Sistemas",
    isEad: true,
    description: "Entenda como projetar e analisar sistemas computacionais.",
    cashValue: 280.0,
    installmentValue: 28.0,
    numberOfInstallments: 10,
  },
  {
    id: 19,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 19",
    technology: "Redes de Computadores Avançadas",
    isEad: false,
    description: "Aprofunde seus conhecimentos em redes e infraestrutura.",
    cashValue: 400.0,
    installmentValue: 40.0,
    numberOfInstallments: 10,
  },
  {
    id: 20,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 20",
    technology: "Cibersegurança",
    isEad: true,
    description: "Aprenda técnicas avançadas para proteger sistemas e redes.",
    cashValue: 500.0,
    installmentValue: 50.0,
    numberOfInstallments: 10,
  },
  {
    id: 21,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 21",
    technology: "Automação Industrial",
    isEad: true,
    description: "Domine tecnologias para automação de processos industriais.",
    cashValue: 600.0,
    installmentValue: 60.0,
    numberOfInstallments: 10,
  },
  {
    id: 22,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 22",
    technology: "Programação Front-End",
    isEad: false,
    description:
      "Aprenda HTML, CSS e JavaScript para desenvolver interfaces modernas.",
    cashValue: 250.0,
    installmentValue: 25.0,
    numberOfInstallments: 10,
  },
  {
    id: 23,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 23",
    technology: "Programação Back-End",
    isEad: true,
    description: "Desenvolva sistemas robustos com Node.js e Python.",
    cashValue: 300.0,
    installmentValue: 30.0,
    numberOfInstallments: 10,
  },
  {
    id: 24,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 24",
    technology: "Game Development",
    isEad: false,
    description: "Crie jogos utilizando Unity e Unreal Engine.",
    cashValue: 700.0,
    installmentValue: 70.0,
    numberOfInstallments: 10,
  },
  {
    id: 25,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 25",
    technology: "Internet das Coisas (IoT)",
    isEad: true,
    description:
      "Explore como conectar dispositivos e sensores para criar soluções inovadoras.",
    cashValue: 450.0,
    installmentValue: 45.0,
    numberOfInstallments: 10,
  },
  {
    id: 26,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 26",
    technology: "Engenharia de Dados",
    isEad: true,
    description: "Construa pipelines para processamento e análise de dados.",
    cashValue: 520.0,
    installmentValue: 52.0,
    numberOfInstallments: 10,
  },
  {
    id: 27,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 27",
    technology: "Metodologias Ágeis",
    isEad: false,
    description: "Aprenda Scrum, Kanban e práticas ágeis para projetos.",
    cashValue: 300.0,
    installmentValue: 30.0,
    numberOfInstallments: 10,
  },
  {
    id: 28,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 28",
    technology: "Computação Quântica",
    isEad: true,
    description:
      "Entenda os conceitos básicos e aplicações da computação quântica.",
    cashValue: 800.0,
    installmentValue: 80.0,
    numberOfInstallments: 10,
  },
  {
    id: 29,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 29",
    technology: "Design Thinking",
    isEad: true,
    description: "Aprenda a resolver problemas de forma criativa e inovadora.",
    cashValue: 240.0,
    installmentValue: 24.0,
    numberOfInstallments: 10,
  },
  {
    id: 30,
    imageUrl: "/assets/outhers/Carousel.png",
    title: "Tecnologia da Informação 30",
    technology: "Processamento de Imagens",
    isEad: false,
    description:
      "Desenvolva habilidades em processamento e análise de imagens digitais.",
    cashValue: 380.0,
    installmentValue: 38.0,
    numberOfInstallments: 10,
  },
];
